# Generated by Django 3.2.3 on 2021-05-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_text', models.CharField(max_length=200)),
                ('pub_date', models.CharField(max_length=200)),
            ],
        ),
    ]
